source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/xierb123/XRBSpecs.git'

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'XRBFrame' do
    pod 'Moya', '~> 14.0.0'
    pod 'WCDBSwift', '~> 1.0.1'
    pod 'CleanJSON', '~> 1.0.8'
    pod 'CryptoSwift', '~> 1.3.5'
    pod 'Kingfisher', '~> 6.3.0'
    pod 'KeychainAccess', '~> 4.1.0'
    pod 'IBAnimatable', '~> 6.0.0'
    pod 'SwiftyGif', '~> 5.3.0'
    pod 'SnapKit', '~> 5.0.1'
    pod 'SwiftTimer', '~> 2.0'
    pod 'Toast-Swift', '~> 5.0.1'
    pod 'swiftScan'
    pod 'ZLPhotoBrowser', '~> 4.1.6'
    pod 'DeviceKit', '~> 4.2.1'
    pod 'Tiercel', '~> 3.2.1'
    pod 'ZFPlayer/ControlView', '~> 4.0'
    pod 'ZFPlayer/AVPlayer', '~> 4.0'
    pod 'ESPullToRefresh', '~> 2.9.3'
    pod "ESTabBarController-swift", '~> 2.8.0'
    pod 'EmptyDataSet-Swift', '~> 5.0.0'
    pod 'IQKeyboardManagerSwift', '~> 6.5.6'
    pod 'UMCPush', '~> 3.3.1'
    pod 'WechatOpenSDK', '1.8.6.2'
    pod "Weibo_SDK"
    pod 'Bugly', '~> 2.5.90'
    pod 'lottie-ios', '~> 3.1.8'
    pod 'Starscream', '~> 4.0.0'
    pod 'CameraManager', '~> 5.1.3'
    pod 'JXPagingView/Paging', '~> 2.1.0'
    pod 'JXSegmentedView', '~> 1.2.7'
    pod 'DanmakuKit', '~> 1.2.0'
    pod 'XRBModule'
end
